#!/bin/sh

export BROWSER=firefox
export EDITOR=nvim
export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for JetBrains IDEs

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
$HOME/.local/bin/eww open bar &
dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom/picom.conf &
hsetroot -fill "$HOME/.config/bspwm/wall.jpg"
$HOME/.config/bspwm/bin/ewwFlScr &

bspc monitor -d 1 2 3 4 5 6
rule firefox                        desktop=1
rule discord                        desktop=2
rule Lutris                         desktop=3 state=floating
rule Steam                          desktop=4
rule Viewnior                       state=floating

config pointer_modifier             Mod4
config window_gap                   16
config left_padding                 46

config split_ratio                  0.62
config borderless_monocle           true
config gapless_monocle              true

start $HOME/.local/bin/brdr

